openapi: 3.0.0
info:
  description: |
    This is a sample Flower Shop server.  
    This includes the Buy REST APIs.
    You can find
    out more about Swagger at
    [http://swagger.io](http://swagger.io) or on
    [irc.freenode.net, #swagger](http://swagger.io/irc/).
  version: 2.0.0
  title: Flower Shop -- Buy
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: rosemary.charnley@smartbear.com
  license:
    name: Apache 2.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: 'https://virtserver.swaggerhub.com/Charnley-Test/Buy-Flower-Shop/2.0.0'
  # Development Server
  - description: Development Server
    url: 'https://development.flowershop.io/v1'
  # Staging Server
  - description: Staging Server
    url: 'https://staging.flowershop.io/v1'
  # Production Server
  - description: Production Server
    url: 'https://api.flowershop.io/v1'
tags:
  - name: Shop
    description: Rest APIs for Shop
  - name: Shopping Cart
    description: Rest APIs for Shopping Cart
  - name: Check Out
    description: Rest APIs for Check Out
paths:
  /shop:
    get:
      tags:
        - Shop
      summary: Get all flowers to shop.
      responses:
        '200':
          description: List of all flowers.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'https://api.swaggerhub.com/domains/Charnley-Test/Global-Components-Flower-Shop/1.0.0#/components/examples/flower'
      #'#/components/schemas/Flower'
      operationId: getAllFlower
      description: Get all flowers for all users!
    post:
      tags:
        - Shop
      summary: Add a flower to shop
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Flower'
      responses:
        '200':
          description: Flower item successfully added.
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/Charnley-Test/Global-Components-Flower-Shop/1.0.0#/components/examples/flower'
  # '#/components/schemas/Flower'
  '/{user_id}/shoppingcart/{session_id}':
    get:
      tags:
        - Shopping Cart
      summary: Get shopping cart session.
      parameters:
        - name: user_id
          in: path
          description: User ID to load shopping cart.
          required: true
          schema:
            type: string
        - name: session_id
          in: path
          description: Session ID to load shopping cart.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of all flowers.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ShoppingCart'
      operationId: ''
      description: Get shopping cart session. This is a update
      security: []
    post:
      tags:
        - Shopping Cart
      summary: Add item to shopping cart session.
      parameters:
        - name: user_id
          in: path
          description: User ID to load shopping cart.
          required: true
          schema:
            type: string
        - name: session_id
          in: path
          description: Session ID to load shopping cart.
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShoppingCart'
      responses:
        '200':
          description: List of all flowers.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ShoppingCart'
      description: This is a description
    delete:
      tags:
        - Shopping Cart
      summary: Add item to shopping cart session.
      parameters:
        - name: user_id
          in: path
          description: User ID to load shopping cart.
          required: true
          schema:
            type: string
        - name: session_id
          in: path
          description: Session ID to load shopping cart.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of all flowers.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ShoppingCart'
  '/{user_id}/checkout/{session_id}':
    get:
      tags:
        - Check Out
      summary: Get checkout session.
      parameters:
        - name: user_id
          in: path
          description: User ID to load shopping cart.
          required: true
          schema:
            type: string
        - name: session_id
          in: path
          description: Session ID to load shopping cart.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of all flowers.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Flower'
    post:
      tags:
        - Check Out
      summary: Add item to check out session.
      parameters:
        - name: user_id
          in: path
          description: User ID to load shopping cart.
          required: true
          schema:
            type: string
        - name: session_id
          in: path
          description: Session ID to load shopping cart.
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Flower'
      responses:
        '200':
          description: List of all flowers.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Flower'
    delete:
      tags:
        - Check Out
      summary: Add item to check out session.
      parameters:
        - name: user_id
          in: path
          description: User ID to load shopping cart.
          required: true
          schema:
            type: string
        - name: session_id
          in: path
          description: Session ID to load shopping cart.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of all flowers.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Flower'
components:
  schemas:
    Flower:
      type: object
      properties:
        id:
          type: integer
          example: 2
        name:
          type: string
          example: Sun Flower
        primary-color:
          type: string
          example: Red
        secondary-color:
          type: string
          example: brown
        Desciption:
          type: string
          example: Tall weed flower
        price:
          type: number
          example: 3.99
        category:
          type: string
          example: weed
    ShoppingCart:
      type: object
      properties:
        id:
          type: integer
          example: 4
        cart_items:
          type: array
          items:
            $ref: '#/components/schemas/Flower'
        discount_code:
          type: string
          example: SALE20
        sub_total:
          type: number
          example: 10.87
        tax:
          type: number
          example: 2
        total:
          type: number
          example: 12.87
x-azure-api-id: sh-f82e3994-a35e-4539-b396-d5747df76672