openapi: 3.0.0
info:
  description: 
  version: 3.0.0
  title: Flower Shop -- Buy
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: rosemary.charnley@smartbear.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - description: SwaggerHub API Auto Mocking
    url: 'https://virtserver.swaggerhub.com/Charnley-Test/Buy-Flower-Shop/3.0.0'
  - description: Development Server
    url: 'https://development.flowershop.io/v1'
  - description: Staging Server
    url: 'https://staging.flowershop.io/v1'
  - description: Production Server
    url: 'https://api.flowershop.io/v1'
tags:
  - name: Shop
    description: Rest APIs for Shop
  - name: Shopping Cart
    description: Rest APIs for Shopping Cart
  - name: Check Out
    description: Rest APIs for Check Out
paths:
  /shop:
    get:
      tags:
        - Shop
      summary: Get all flowers to shop.
      responses:
        '200':
          description: List of all flowers.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Flower'
      description: 'add a description '
    post:
      tags:
        - Shop
      summary: Add a flower to shop
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Flower'
      responses:
        '200':
          description: Flower item successfully added.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Flower'
      description: description
  '/{user_id}/shoppingcart/{session_id}':
    get:
      tags:
        - Shopping Cart
      summary: Get shopping cart session.
      parameters:
        - name: user_id
          in: path
          description: User ID to load shopping cart.
          required: true
          schema:
            type: string
        - name: session_id
          in: path
          description: Session ID to load shopping cart.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of all flowers.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ShoppingCart'
    post:
      tags:
        - Shopping Cart
      summary: Add item to shopping cart session.
      parameters:
        - name: user_id
          in: path
          description: User ID to load shopping cart.
          required: true
          schema:
            type: string
        - name: session_id
          in: path
          description: Session ID to load shopping cart.
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShoppingCart'
      responses:
        '200':
          description: List of all flowers.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ShoppingCart'
    delete:
      tags:
        - Shopping Cart
      summary: Remove item from shopping cart session.
      parameters:
        - name: user_id
          in: path
          description: User ID to load shopping cart.
          required: true
          schema:
            type: string
        - name: session_id
          in: path
          description: Session ID to load shopping cart.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of all flowers.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ShoppingCart'
  '/{user_id}/checkout/{session_id}':
    get:
      tags:
        - Check Out
      summary: Get checkout session.
      parameters:
        - name: user_id
          in: path
          description: User ID to load shopping cart.
          required: true
          schema:
            type: string
        - name: session_id
          in: path
          description: Session ID to load shopping cart.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of all flowers.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Flower'
    post:
      tags:
        - Check Out
      summary: Add item to check out session.
      parameters:
        - name: user_id
          in: path
          description: User ID to load shopping cart.
          required: true
          schema:
            type: string
        - name: session_id
          in: path
          description: Session ID to load shopping cart.
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Flower'
      responses:
        '200':
          description: List of all flowers.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Flower'
    delete:
      tags:
        - Check Out
      summary: Remove item from check out session.
      parameters:
        - name: user_id
          in: path
          description: User ID to load shopping cart.
          required: true
          schema:
            type: string
        - name: session_id
          in: path
          description: Session ID to load shopping cart.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of all flowers.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Flower'
components:
  schemas:
    Flower:
      type: object
      properties:
        id:
          type: integer
          example: 2
        name:
          type: string
          example: Sun Flower
        primary-color:
          type: string
          example: Red
        secondary-color:
          type: string
          example: brown
        Description:
          type: string
          example: Tall weed flower
        price:
          type: number
          example: 3.99
        category:
          type: string
          example: weed
    ShoppingCart:
      type: object
      properties:
        id:
          type: integer
          example: 4
        cart_items:
          type: array
          items:
            $ref: '#/components/schemas/Flower'
        discount_code:
          type: string
          example: SALE20
        sub_total:
          type: number
          example: 10.87
        tax:
          type: number
          example: 2
        total:
          type: number
          example: 12.87
    Receipt:
      type: object
      properties:
        id:
          type: integer
          example: 1
        time:
          type: string
          format: date-time
          example: '2023-10-01T12:00:00Z'
        location:
          type: string
          example: '123 Flower St, Bloomtown'
x-azure-api-id: sh-f82e3994-a35e-4539-b396-d5747df76672
x-internal: true