/*
 * Flower Shop -- Billing
 *
 * This is a sample Flower Shop server.   This includes the Billing REST APIs. You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/). 
 *
 * API version: 1.0.0
 * Contact: rosemary.charnley@smartbear.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Person struct {

	Id string `json:"id"`

	Firstname string `json:"firstname"`

	Lastname string `json:"lastname,omitempty"`

	Email string `json:"email"`

	Phonenumber string `json:"phonenumber,omitempty"`

	Address string `json:"address,omitempty"`
}
