/*
 * Flower Shop -- Billing
 *
 * This is a sample Flower Shop server.   This includes the Billing REST APIs. You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/). 
 *
 * API version: 1.0.0
 * Contact: rosemary.charnley@smartbear.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/Charnley-Test/Billing-Flower-Shop/1.0.0/",
		Index,
	},

	Route{
		"BillIdGet",
		strings.ToUpper("Get"),
		"/Charnley-Test/Billing-Flower-Shop/1.0.0/bill/{id}",
		BillIdGet,
	},

	Route{
		"BillPost",
		strings.ToUpper("Post"),
		"/Charnley-Test/Billing-Flower-Shop/1.0.0/bill",
		BillPost,
	},

	Route{
		"ProcessPost",
		strings.ToUpper("Post"),
		"/Charnley-Test/Billing-Flower-Shop/1.0.0/process",
		ProcessPost,
	},

	Route{
		"ReceiptIdGet",
		strings.ToUpper("Get"),
		"/Charnley-Test/Billing-Flower-Shop/1.0.0/receipt/{id}",
		ReceiptIdGet,
	},

	Route{
		"ReceiptPost",
		strings.ToUpper("Post"),
		"/Charnley-Test/Billing-Flower-Shop/1.0.0/receipt",
		ReceiptPost,
	},
}
